### ISSUE TITLE
App fails to launch if current OS regional setting uses unexpected decimal separator

### ISSUE THREAD

**Issue by Kuziz** [Nordgaren/DS-Gadget-for-Remastest#2]
`System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Single.Parse(String s)
   at DS_Gadget.DSPhysique..cctor()`

Issue occurred on a computer running Windows 10 in Brazil/PT-BR locale. Switching to English UK worked around the issue and the application launched without a problem.
Most likely has to do something with CultureInfo.

Haven't tested other versions of Gadget, only this one in particular.

**Comment by Nordgaren** [comment]
Yea, sorry. I have a patch for this, but haven't pushed it because i haven't gotten a lot of feedback on if it works or not. I can send you a build, if you have Discord or something.
